-- Minimal legacy pantry schema used by the production-divergence CI scenario.
-- The real project already owns these tables; scenario B previously simulated
-- only the V2 catalog schemas, so post-snapshot pantry migrations had no base.

create table if not exists public.canonical_foods (
  id bigint generated by default as identity primary key,
  canonical_name text not null unique
);

create table if not exists public.archetypes (
  id bigint generated by default as identity primary key,
  name text not null,
  canonical_food_id bigint references public.canonical_foods(id),
  open_shelf_life_days integer,
  open_shelf_life_days_pantry integer,
  open_shelf_life_days_fridge integer,
  open_shelf_life_days_freezer integer
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  shelf_life_after_opening_days integer
);

create table if not exists public.inventory_lots (
  id uuid primary key default gen_random_uuid(),
  user_id uuid default auth.uid(),
  archetype_id bigint references public.archetypes(id),
  product_id uuid references public.products(id),
  qty_remaining numeric not null default 0,
  initial_qty numeric not null,
  unit varchar(20) not null default 'u',
  storage_method varchar(20) not null default 'pantry',
  storage_place varchar(80),
  expiration_date date,
  adjusted_expiration_date date,
  is_opened boolean default false,
  opened_at timestamp,
  is_containerized boolean default false,
  container_size numeric,
  container_unit varchar(20),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
