-- Stubs minimaux pour le scénario B de la CI (simulation prod divergente).
-- Ces tables sont dans les migrations « trust » (appliquées en prod avant le
-- snapshot) et ne sont donc PAS appliquées par apply-migrations.sh dans la
-- simulation. Elles doivent exister pour que 20260717000001_p1_cooked_dish_reservations
-- puisse s'appliquer (ALTER TABLE, REFERENCES FK, CREATE POLICY WITH CHECK).
--
-- IMPORTANT : structure strictement minimale — uniquement les colonnes
-- nécessaires à la syntaxe des DDL de la migration P1.
-- Les colonnes complètes sont portées par les migrations « trust » en prod.

-- cooked_dishes : FK cible de inventory_reservations.cooked_dish_id.
CREATE TABLE IF NOT EXISTS public.cooked_dishes (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         uuid,
  name            text NOT NULL DEFAULT '',
  portions_cooked numeric NOT NULL DEFAULT 0,
  portions_remaining numeric NOT NULL DEFAULT 0,
  expiration_date date
);

-- meal_plan_versions : référencé par les CREATE POLICY WITH CHECK sur
-- inventory_reservations (sous-requête EXISTS avec JOIN).
CREATE TABLE IF NOT EXISTS public.meal_plan_versions (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid NOT NULL,
  import_id  bigint NOT NULL,
  status     text NOT NULL DEFAULT 'published'
);

-- meal_plan_slots : référencé par les CREATE POLICY WITH CHECK sur
-- inventory_reservations (JOIN meal_plan_versions).
CREATE TABLE IF NOT EXISTS public.meal_plan_slots (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         uuid NOT NULL,
  plan_version_id uuid NOT NULL REFERENCES public.meal_plan_versions(id) ON DELETE CASCADE
);

-- inventory_reservations : table cible du ALTER TABLE de la migration P1.
-- Les colonnes déclarées ici sont celles référencées dans les WHERE des policies.
-- inventory_lots : référencé par les politiques RLS recréées de la migration P1
-- (les corps de fonctions plpgsql ne sont pas validés à la création, mais les
-- politiques le sont — sans cette table, CREATE POLICY échoue).
CREATE TABLE IF NOT EXISTS public.inventory_lots (
  id      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL
);

CREATE TABLE IF NOT EXISTS public.inventory_reservations (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           uuid NOT NULL,
  plan_version_id   uuid,
  slot_id           uuid,
  lot_id            uuid,
  ingredient_name   text,
  reserved_quantity numeric,
  reserved_unit     text,
  needed_quantity   numeric,
  needed_unit       text,
  status            text NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active', 'consumed', 'released', 'expired')),
  consumed_at       timestamptz,
  released_at       timestamptz,
  metadata          jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at        timestamptz NOT NULL DEFAULT now()
);

-- nutrition_plan_prep_tasks : référencé par planned_productions.source_task_id
-- (FK de la migration P2). Structure minimale : id (bigint PK), user_id, import_id,
-- done — seuls les colonnes nécessaires à la syntaxe DDL P2.
CREATE TABLE IF NOT EXISTS public.nutrition_plan_prep_tasks (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid,
  import_id  bigint,
  done       boolean NOT NULL DEFAULT false
);

-- meal_plan_slots.meal_date et meal_plan_slots.meal_type sont lus dans le corps
-- de la RPC P2 (publish_closed_loop_plan). La RPC est PL/pgSQL compilé
-- à l'exécution, donc l'absence de colonnes ne bloque pas le CREATE OR REPLACE.
-- On les ajoute ici pour permettre les assertions de round-trip futures.
ALTER TABLE public.meal_plan_slots ADD COLUMN IF NOT EXISTS meal_date date;
ALTER TABLE public.meal_plan_slots ADD COLUMN IF NOT EXISTS meal_type text;

-- RLS nécessaire pour que les DROP POLICY IF EXISTS / CREATE POLICY
-- s'appliquent sans erreur.
ALTER TABLE public.inventory_reservations ENABLE ROW LEVEL SECURITY;

-- Politique SELECT minimale (exigée par Postgres pour activer RLS sur la table).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename  = 'inventory_reservations'
      AND policyname = 'inventory_reservations_select_own'
  ) THEN
    EXECUTE $pol$
      CREATE POLICY inventory_reservations_select_own
        ON public.inventory_reservations
        FOR SELECT USING ((SELECT auth.uid()) = user_id)
    $pol$;
  END IF;
END $$;
