-- Stubs minimaux pour le scénario B de la CI (simulation prod divergente).
-- Ces tables sont dans les migrations « trust » appliquées en production avant
-- le snapshot. La CI les recrée avec les colonnes nécessaires aux migrations
-- P1/P2 et à la transaction de matérialisation des tâches.

CREATE TABLE IF NOT EXISTS public.cooked_dishes (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id               uuid,
  name                  text NOT NULL DEFAULT '',
  portions_cooked       numeric NOT NULL DEFAULT 0,
  portions_remaining    numeric NOT NULL DEFAULT 0,
  storage_method        text NOT NULL DEFAULT 'fridge',
  cooked_at             timestamptz NOT NULL DEFAULT now(),
  expiration_date       date,
  notes                 text,
  source_meal_type      text,
  kcal_per_portion      numeric,
  protein_g_per_portion numeric,
  carbs_g_per_portion   numeric,
  fat_g_per_portion     numeric,
  fiber_g_per_portion   numeric
);

CREATE TABLE IF NOT EXISTS public.household_members (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id              uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name                 text NOT NULL,
  portion_multiplier   numeric(4,2) NOT NULL DEFAULT 1,
  active               boolean NOT NULL DEFAULT true,
  preferences          jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.meal_plan_versions (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id             uuid NOT NULL,
  import_id           bigint NOT NULL,
  status              text NOT NULL DEFAULT 'published',
  source              text NOT NULL DEFAULT 'closed_loop',
  window_start        date NOT NULL DEFAULT current_date,
  window_end          date NOT NULL DEFAULT current_date,
  validation_summary  jsonb NOT NULL DEFAULT '{}'::jsonb,
  rules_version       text NOT NULL DEFAULT 'closed-loop-v1',
  updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.meal_plan_slots (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         uuid NOT NULL,
  plan_version_id uuid NOT NULL REFERENCES public.meal_plan_versions(id) ON DELETE CASCADE,
  meal_date       date,
  meal_type       text,
  servings        numeric NOT NULL DEFAULT 1,
  nutrition_total jsonb NOT NULL DEFAULT '{}'::jsonb,
  stock_summary   jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- Le fixture stock historique crée déjà inventory_lots. Les ALTER gardent ce
-- fichier idempotent si la structure évolue.
ALTER TABLE public.inventory_lots ADD COLUMN IF NOT EXISTS canonical_food_id bigint;
ALTER TABLE public.inventory_lots ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

ALTER TABLE public.canonical_foods ADD COLUMN IF NOT EXISTS density_g_per_ml numeric;
ALTER TABLE public.canonical_foods ADD COLUMN IF NOT EXISTS unit_weight_grams numeric;

CREATE TABLE IF NOT EXISTS public.inventory_reservations (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           uuid NOT NULL,
  plan_version_id   uuid,
  slot_id           uuid,
  lot_id             uuid,
  ingredient_name   text,
  reserved_quantity numeric,
  reserved_unit     text,
  needed_quantity   numeric,
  needed_unit       text,
  status            text NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active', 'consumed', 'released', 'expired')),
  consumed_at       timestamptz,
  released_at       timestamptz,
  metadata          jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.nutrition_plan_prep_tasks (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id             uuid,
  import_id           bigint,
  plan_version_id     uuid,
  meal_plan_slot_id   uuid,
  task_type           text NOT NULL DEFAULT 'prepare_recipe',
  workflow_status     text NOT NULL DEFAULT 'pending',
  done                boolean NOT NULL DEFAULT false,
  done_at             timestamptz
);

CREATE TABLE IF NOT EXISTS public.prep_task_dependencies (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id              uuid NOT NULL,
  plan_version_id      uuid NOT NULL,
  task_id              bigint NOT NULL REFERENCES public.nutrition_plan_prep_tasks(id) ON DELETE CASCADE,
  depends_on_task_id   bigint NOT NULL REFERENCES public.nutrition_plan_prep_tasks(id) ON DELETE CASCADE,
  created_at           timestamptz NOT NULL DEFAULT now()
);

-- Journal immuable minimal requis par set_planned_task_done. En production la
-- table complète est fournie par 20260711_cooking_sessions.sql.
CREATE TABLE IF NOT EXISTS public.inventory_movements (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         uuid NOT NULL,
  lot_id          uuid,
  session_id      uuid,
  movement_type   text NOT NULL,
  quantity_before numeric,
  quantity_delta  numeric NOT NULL,
  quantity_after  numeric,
  created_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.inventory_reservations ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'inventory_reservations'
      AND policyname = 'inventory_reservations_select_own'
  ) THEN
    EXECUTE $pol$
      CREATE POLICY inventory_reservations_select_own
        ON public.inventory_reservations
        FOR SELECT USING ((SELECT auth.uid()) = user_id)
    $pol$;
  END IF;
END $$;
