INSERT INTO canonical_foods (canonical_name, primary_unit, category_id) VALUES ('lait de chèvre', 'ml', NULL);
INSERT INTO canonical_foods (canonical_name, primary_unit, category_id) VALUES ('pain', 'g', NULL);
INSERT INTO canonical_foods (canonical_name, primary_unit, category_id) VALUES ('farine de blé', 'g', NULL);
INSERT INTO canonical_foods (canonical_name, primary_unit, category_id) VALUES ('vin', 'ml', NULL);
INSERT INTO canonical_foods (canonical_name, primary_unit, category_id) VALUES ('bière', 'ml', NULL);
INSERT INTO canonical_foods (canonical_name, primary_unit, category_id) VALUES ('pâtes', 'g', NULL);
INSERT INTO canonical_foods (canonical_name, primary_unit, category_id) VALUES ('riz', 'g', NULL);
INSERT INTO canonical_foods (canonical_name, primary_unit, category_id) VALUES ('soja', 'g', NULL);
INSERT INTO canonical_foods (canonical_name, primary_unit, category_id) VALUES ('blé', 'g', NULL);
INSERT INTO cultivars (name, canonical_food_id, specificity) VALUES ('morue', 2004, 'salé/séché');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('emmental', 7001, 'fromage affiné', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('gruyère', 7001, 'fromage affiné', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('comté', 7001, 'fromage affiné', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('parmesan', 7001, 'fromage affiné', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('mozzarella', 7001, 'fromage frais', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('ricotta', 7001, 'fromage frais', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('pecorino', 7001, 'fromage affiné', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('bœuf haché', 14011, 'haché', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('bœuf en morceaux', 14011, 'en morceaux', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('steak de bœuf', 14011, 'steak', 'pièce');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('entrecôte', 14011, 'entrecôte', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('filet de bœuf', 14011, 'filet', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('côte de bœuf', 14011, 'côte', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('veau haché', 8015, 'haché', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('veau en morceaux', 8015, 'en morceaux', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('escalope de veau', 8015, 'escalope', 'pièce');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('rôti de veau', 8015, 'rôti', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('paupiette de veau', 8015, 'paupiette', 'pièce');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('agneau haché', 4001, 'haché', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('agneau en morceaux', 4001, 'en morceaux', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('côtelette d'agneau', 4001, 'côtelette', 'pièce');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('épaule d'agneau', 4001, 'épaule', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('gigot d'agneau', 4001, 'gigot', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('lardons', 2051, 'lardons', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('bacon', 2051, 'bacon', 'tranche');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('jambon cuit', 2051, 'jambon cuit', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('jambon cru', 2051, 'jambon cru', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('saucisse', 2051, 'saucisse', 'pièce');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('chair à saucisse', 2051, 'chair à saucisse', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('boudin noir', 2051, 'boudin', 'pièce');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('saumon fumé', 2062, 'fumé', 'g');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('bouillon de bœuf', 14011, 'bouillon', 'ml');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('bouillon de volaille', 2054, 'bouillon', 'ml');
INSERT INTO archetypes (name, canonical_food_id, process, primary_unit) VALUES ('fumet de poisson', 2004, 'fumet', 'ml');