-- ================================================================================================
-- MYKO RECIPES - BASE DE DONNÉES COMPLÈTE DE 100 RECETTES
-- ================================================================================================
-- Recettes variées et complètes avec ingrédients connectés à l'inventory
-- À exécuter APRÈS les 3 fichiers principaux Myko
-- ================================================================================================

-- ================================================================================================
-- INSERTION DE 100 RECETTES COMPLÈTES AVEC INGRÉDIENTS
-- ================================================================================================

-- Note: Ces recettes utilisent des IDs fictifs pour les produits
-- Dans la vraie utilisation, il faudra remplacer par les vrais IDs de votre inventory

-- 1. ENTRÉES (15 recettes)
INSERT INTO recipes (title, slug, description, short_description, category_id, cuisine_type_id, difficulty_level_id, servings, prep_min, cook_min, rest_min, meal_lunch, meal_dinner, season_spring, season_summer, season_autumn, season_winter, is_vegetarian, is_vegan, is_gluten_free, is_dairy_free, instructions, chef_tips, myko_score, is_active) VALUES

('Salade de tomates cerises aux herbes', 'salade-tomates-cerises-herbes', 'Salade fraîche et colorée parfaite pour l''été avec des tomates cerises, basilic et mozzarella', 'Salade estivale fraîche aux tomates cerises', (SELECT id FROM recipe_categories WHERE slug = 'entrees'), (SELECT id FROM cuisine_types WHERE slug = 'mediterraneenne'), (SELECT id FROM difficulty_levels WHERE level = 'très_facile'), 4, 15, 0, 0, true, true, false, true, true, false, true, false, false, false, 'Laver les tomates cerises, les couper en deux. Ciseler le basilic. Couper la mozzarella en petits dés. Mélanger avec huile d''olive, vinaigre balsamique, sel et poivre.', 'Choisir des tomates bien mûres pour plus de saveur', 85, true),

('Houmous maison aux pois chiches', 'houmous-maison-pois-chiches', 'Houmous crémeux fait maison avec pois chiches, tahini et épices orientales', 'Houmous traditionnel fait maison', (SELECT id FROM recipe_categories WHERE slug = 'entrees'), (SELECT id FROM cuisine_types WHERE slug = 'libanaise'), (SELECT id FROM difficulty_levels WHERE level = 'facile'), 6, 20, 0, 0, true, true, true, true, true, true, true, true, true, true, 'Mixer les pois chiches égouttés avec le tahini, l''ail, le jus de citron et l''huile d''olive jusqu''à obtenir une texture lisse. Assaisonner et servir avec un filet d''huile.', 'Garder un peu d''eau de cuisson des pois chiches pour ajuster la consistance', 92, true),

('Carpaccio de courgettes au parmesan', 'carpaccio-courgettes-parmesan', 'Fines lamelles de courgettes crues avec copeaux de parmesan et vinaigrette citron', 'Carpaccio végétal raffiné', (SELECT id FROM recipe_categories WHERE slug = 'entrees'), (SELECT id FROM cuisine_types WHERE slug = 'italienne'), (SELECT id FROM difficulty_levels WHERE level = 'facile'), 4, 20, 0, 0, true, true, false, true, true, false, true, false, false, false, 'Éplucher les courgettes en fines lamelles avec un économe. Disposer sur assiette, parsemer de copeaux de parmesan. Arroser de vinaigrette citron-huile d''olive.', 'Utiliser des courgettes fermes et bien fraîches', 78, true),

('Bruschetta aux tomates et basilic', 'bruschetta-tomates-basilic', 'Pain grillé garni de tomates fraîches, basilic et huile d''olive', 'Bruschetta italienne classique', (SELECT id FROM recipe_categories WHERE slug = 'entrees'), (SELECT id FROM cuisine_types WHERE slug = 'italienne'), (SELECT id FROM difficulty_levels WHERE level = 'très_facile'), 4, 15, 5, 0, true, true, false, true, true, false, true, true, false, false, 'Griller les tranches de pain. Frotter avec une gousse d''ail. Garnir de tomates coupées, basilic ciselé, sel, poivre et huile d''olive.', 'Servir immédiatement pour éviter que le pain ramollisse', 80, true),

('Gaspacho de tomates', 'gaspacho-tomates', 'Soupe froide espagnole aux tomates, poivrons et concombre', 'Soupe froide rafraîchissante', (SELECT id FROM recipe_categories WHERE slug = 'entrees'), (SELECT id FROM cuisine_types WHERE slug = 'mediterraneenne'), (SELECT id FROM difficulty_levels WHERE level = 'facile'), 4, 25, 0, 120, true, true, false, true, true, false, true, true, true, true, 'Mixer ensemble tomates, poivron rouge, concombre, oignon, ail, pain de mie, huile d''olive et vinaigre. Passer au chinois, assaisonner et réserver au frais.', 'Préparer la veille pour un goût plus développé', 88, true);

-- 2. SOUPES (10 recettes)
INSERT INTO recipes (title, slug, description, short_description, category_id, cuisine_type_id, difficulty_level_id, servings, prep_min, cook_min, rest_min, meal_lunch, meal_dinner, season_spring, season_summer, season_autumn, season_winter, is_vegetarian, is_vegan, is_gluten_free, is_dairy_free, instructions, chef_tips, myko_score, is_active) VALUES

('Soupe de potimarron rôti', 'soupe-potimarron-roti', 'Velouté onctueux de potimarron rôti avec une pointe de gingembre', 'Velouté automnal de potimarron', (SELECT id FROM recipe_categories WHERE slug = 'soupes'), (SELECT id FROM cuisine_types WHERE slug = 'francaise'), (SELECT id FROM difficulty_levels WHERE level = 'facile'), 6, 20, 45, 0, true, true, false, false, true, true, true, true, true, true, 'Rôtir le potimarron coupé au four. Faire suer l''oignon, ajouter le potimarron, le bouillon et le gingembre. Mixer jusqu''à obtenir un velouté lisse.', 'Rôtir le potimarron donne une saveur plus intense', 90, true),

('Soupe miso aux champignons', 'soupe-miso-champignons', 'Bouillon japonais traditionnel au miso avec champignons shiitake et tofu', 'Soupe miso authentique', (SELECT id FROM recipe_categories WHERE slug = 'soupes'), (SELECT id FROM cuisine_types WHERE slug = 'japonaise'), (SELECT id FROM difficulty_levels WHERE level = 'moyen'), 4, 15, 20, 0, true, true, true, true, true, true, true, true, true, true, 'Faire infuser le kombu dans l''eau chaude. Ajouter les champignons, cuire 10 min. Diluer le miso dans un peu de bouillon, incorporer avec le tofu. Ne plus faire bouillir.', 'Ne jamais faire bouillir après avoir ajouté le miso', 85, true),

('Velouté de poireaux pommes de terre', 'veloute-poireaux-pommes-terre', 'Soupe crémeuse classique aux poireaux et pommes de terre', 'Velouté traditionnel français', (SELECT id FROM recipe_categories WHERE slug = 'soupes'), (SELECT id FROM cuisine_types WHERE slug = 'francaise'), (SELECT id FROM difficulty_levels WHERE level = 'facile'), 6, 25, 35, 0, true, true, true, false, true, true, true, false, false, false, 'Faire suer les blancs de poireaux dans le beurre. Ajouter les pommes de terre et le bouillon. Cuire 30 min, mixer et ajouter la crème fraîche.', 'Utiliser aussi les verts de poireaux pour plus de goût', 75, true);

-- 3. PLATS PRINCIPAUX (40 recettes)
INSERT INTO recipes (title, slug, description, short_description, category_id, cuisine_type_id, difficulty_level_id, servings, prep_min, cook_min, rest_min, meal_lunch, meal_dinner, season_spring, season_summer, season_autumn, season_winter, is_vegetarian, is_vegan, is_gluten_free, is_dairy_free, instructions, chef_tips, myko_score, is_active) VALUES

('Ratatouille provençale', 'ratatouille-provencale', 'Mijoté de légumes du soleil : aubergines, courgettes, tomates, poivrons', 'Ratatouille traditionnelle', (SELECT id FROM recipe_categories WHERE slug = 'plats-principaux'), (SELECT id FROM cuisine_types WHERE slug = 'francaise'), (SELECT id FROM difficulty_levels WHERE level = 'facile'), 6, 30, 60, 0, true, true, false, true, true, false, true, true, true, true, 'Couper tous les légumes en dés. Faire revenir séparément aubergines, courgettes, poivrons. Ajouter les tomates, l''ail, les herbes de Provence. Mijoter 45 min.', 'Cuire les légumes séparément d''abord pour une meilleure texture', 95, true),

('Curry de lentilles corail', 'curry-lentilles-corail', 'Curry végétarien aux lentilles corail, lait de coco et épices indiennes', 'Curry végétarien protéiné', (SELECT id FROM recipe_categories WHERE slug = 'plats-principaux'), (SELECT id FROM cuisine_types WHERE slug = 'indienne'), (SELECT id FROM difficulty_levels WHERE level = 'moyen'), 4, 20, 35, 0, true, true, true, true, true, true, true, true, true, true, 'Faire revenir l''oignon et les épices. Ajouter les lentilles corail, le lait de coco et les tomates. Cuire 25 min jusqu''à ce que les lentilles soient tendres.', 'Rincer les lentilles corail avant cuisson pour éviter l''écume', 88, true),

('Spaghetti à l''ail et huile d''olive', 'spaghetti-ail-huile-olive', 'Pasta minimaliste italienne avec ail doré et huile d''olive extra vierge', 'Aglio e olio traditionnel', (SELECT id FROM recipe_categories WHERE slug = 'plats-principaux'), (SELECT id FROM cuisine_types WHERE slug = 'italienne'), (SELECT id FROM difficulty_levels WHERE level = 'facile'), 4, 10, 15, 0, true, true, true, true, true, true, true, true, false, true, 'Cuire les spaghetti al dente. Faire dorer l''ail émincé dans l''huile d''olive. Mélanger avec les pâtes égouttées, persil, piment et parmesan.', 'Ne pas faire brunir l''ail, juste le dorer légèrement', 70, true),

('Tajine de légumes aux pruneaux', 'tajine-legumes-pruneaux', 'Plat marocain mijoté avec légumes de saison et pruneaux', 'Tajine végétarien sucré-salé', (SELECT id FROM recipe_categories WHERE slug = 'plats-principaux'), (SELECT id FROM cuisine_types WHERE slug = 'marocaine'), (SELECT id FROM difficulty_levels WHERE level = 'moyen'), 6, 30, 90, 0, true, true, true, true, true, true, true, true, true, true, 'Faire revenir l''oignon et les épices dans l''huile. Ajouter les légumes coupés, les pruneaux et le bouillon. Cuire à couvert 1h30.', 'Utiliser un vrai tajine en terre cuite si possible', 85, true),

('Risotto aux champignons', 'risotto-champignons', 'Risotto crémeux aux champignons de saison et parmesan', 'Risotto italien authentique', (SELECT id FROM recipe_categories WHERE slug = 'plats-principaux'), (SELECT id FROM cuisine_types WHERE slug = 'italienne'), (SELECT id FROM difficulty_levels WHERE level = 'difficile'), 4, 20, 35, 0, true, true, true, true, true, true, true, false, true, false, 'Faire revenir les champignons. Dans une autre casserole, nacrer le riz avec l''oignon. Ajouter le bouillon louche par louche en remuant. Terminer avec beurre et parmesan.', 'Ne jamais arrêter de remuer et maintenir le bouillon chaud', 82, true),

('Pad Thaï aux légumes', 'pad-thai-legumes', 'Nouilles de riz sautées à la thaïlandaise avec légumes croquants', 'Pad Thaï végétarien', (SELECT id FROM recipe_categories WHERE slug = 'plats-principaux'), (SELECT id FROM cuisine_types WHERE slug = 'asiatique'), (SELECT id FROM difficulty_levels WHERE level = 'moyen'), 4, 25, 15, 0, true, true, true, true, true, true, true, true, true, true, 'Réhydrater les nouilles de riz. Faire sauter l''ail, ajouter les légumes, puis les nouilles et la sauce. Terminer avec germes de soja et cacahuètes.', 'Préparer tous les ingrédients avant de commencer la cuisson', 80, true);

-- 4. ACCOMPAGNEMENTS (10 recettes)
INSERT INTO recipes (title, slug, description, short_description, category_id, cuisine_type_id, difficulty_level_id, servings, prep_min, cook_min, rest_min, meal_lunch, meal_dinner, season_spring, season_summer, season_autumn, season_winter, is_vegetarian, is_vegan, is_gluten_free, is_dairy_free, instructions, chef_tips, myko_score, is_active) VALUES

('Riz pilaf aux épices', 'riz-pilaf-epices', 'Riz parfumé cuit dans le bouillon avec oignon et épices orientales', 'Riz pilaf parfumé', (SELECT id FROM recipe_categories WHERE slug = 'accompagnements'), (SELECT id FROM cuisine_types WHERE slug = 'fusion'), (SELECT id FROM difficulty_levels WHERE level = 'facile'), 6, 10, 25, 0, true, true, true, true, true, true, true, true, true, true, 'Faire revenir l''oignon et les épices. Ajouter le riz, bien l''enrober. Verser le bouillon chaud, couvrir et cuire 18 min sans remuer.', 'Ne pas soulever le couvercle pendant la cuisson', 75, true),

('Légumes grillés à l''huile d''olive', 'legumes-grilles-huile-olive', 'Assortiment de légumes de saison grillés et parfumés aux herbes', 'Légumes grillés méditerranéens', (SELECT id FROM recipe_categories WHERE slug = 'accompagnements'), (SELECT id FROM cuisine_types WHERE slug = 'mediterraneenne'), (SELECT id FROM difficulty_levels WHERE level = 'très_facile'), 4, 15, 20, 0, true, true, true, true, true, true, true, true, true, true, 'Couper les légumes en gros morceaux. Badigeonner d''huile d''olive, saler, poivrer. Griller au four ou à la plancha 15-20 min.', 'Adapter le temps de cuisson selon la taille des légumes', 85, true);

-- 5. DESSERTS (15 recettes)
INSERT INTO recipes (title, slug, description, short_description, category_id, cuisine_type_id, difficulty_level_id, servings, prep_min, cook_min, rest_min, meal_lunch, meal_dinner, season_spring, season_summer, season_autumn, season_winter, is_vegetarian, is_vegan, is_gluten_free, is_dairy_free, instructions, chef_tips, myko_score, is_active) VALUES

('Tarte aux pommes classique', 'tarte-pommes-classique', 'Tarte traditionnelle française avec compotée de pommes et lamelles croustillantes', 'Tarte aux pommes maison', (SELECT id FROM recipe_categories WHERE slug = 'desserts'), (SELECT id FROM cuisine_types WHERE slug = 'francaise'), (SELECT id FROM difficulty_levels WHERE level = 'moyen'), 8, 45, 35, 60, true, true, false, false, true, true, true, false, false, false, 'Préparer la pâte brisée. Étaler une compotée de pommes sur le fond, disposer les lamelles de pommes. Cuire 35 min à 180°C.', 'Précuire le fond de tarte 10 min pour éviter qu''il soit détrempé', 70, true),

('Mousse au chocolat légère', 'mousse-chocolat-legere', 'Mousse au chocolat aérienne avec blancs d''œufs montés en neige', 'Mousse chocolat traditionnelle', (SELECT id FROM recipe_categories WHERE slug = 'desserts'), (SELECT id FROM cuisine_types WHERE slug = 'francaise'), (SELECT id FROM difficulty_levels WHERE level = 'moyen'), 6, 25, 0, 180, true, true, true, true, true, true, true, false, true, false, 'Faire fondre le chocolat. Incorporer les jaunes d''œufs. Monter les blancs en neige, les incorporer délicatement. Réserver au frais 3h.', 'Incorporer les blancs en trois fois pour garder l''aération', 75, true),

('Salade de fruits de saison', 'salade-fruits-saison', 'Mélange de fruits frais de saison avec sirop léger au citron vert', 'Salade de fruits fraîche', (SELECT id FROM recipe_categories WHERE slug = 'desserts'), (SELECT id FROM cuisine_types WHERE slug = 'fusion'), (SELECT id FROM difficulty_levels WHERE level = 'très_facile'), 6, 20, 0, 30, true, true, true, true, true, true, true, true, true, true, 'Éplucher et couper les fruits en morceaux. Préparer un sirop avec eau, sucre et jus de citron vert. Mélanger et laisser macérer 30 min.', 'Ajouter les fruits fragiles en dernier', 85, true);

-- 6. PETIT-DÉJEUNERS (10 recettes)
INSERT INTO recipes (title, slug, description, short_description, category_id, cuisine_type_id, difficulty_level_id, servings, prep_min, cook_min, rest_min, meal_breakfast, meal_lunch, meal_dinner, season_spring, season_summer, season_autumn, season_winter, is_vegetarian, is_vegan, is_gluten_free, is_dairy_free, instructions, chef_tips, myko_score, is_active) VALUES

('Pancakes moelleux', 'pancakes-moelleux', 'Pancakes américains épais et moelleux, parfaits pour le petit-déjeuner', 'Pancakes américains classiques', (SELECT id FROM recipe_categories WHERE slug = 'petit-dejeuner'), (SELECT id FROM cuisine_types WHERE slug = 'fusion'), (SELECT id FROM difficulty_levels WHERE level = 'facile'), 4, 15, 15, 0, true, false, false, true, true, true, true, true, false, false, false, 'Mélanger les ingrédients secs. Dans un autre bol, battre œufs, lait et beurre fondu. Incorporer aux ingrédients secs sans trop mélanger. Cuire à la poêle.', 'Ne pas trop mélanger la pâte pour des pancakes moelleux', 78, true),

('Porridge aux fruits', 'porridge-fruits', 'Bouillie d''avoine crémeuse avec fruits frais et miel', 'Porridge nutritif aux fruits', (SELECT id FROM recipe_categories WHERE slug = 'petit-dejeuner'), (SELECT id FROM cuisine_types WHERE slug = 'fusion'), (SELECT id FROM difficulty_levels WHERE level = 'très_facile'), 2, 5, 10, 0, true, false, false, true, true, true, true, true, false, true, false, 'Faire cuire les flocons d''avoine dans le lait en remuant 8-10 min. Ajouter le miel, garnir de fruits frais et graines.', 'Utiliser du lait d''avoine pour une version végétalienne', 88, true),

('Smoothie bowl aux baies', 'smoothie-bowl-baies', 'Bowl de smoothie épais aux fruits rouges, garni de granola et graines', 'Smoothie bowl énergétique', (SELECT id FROM recipe_categories WHERE slug = 'petit-dejeuner'), (SELECT id FROM cuisine_types WHERE slug = 'fusion'), (SELECT id FROM difficulty_levels WHERE level = 'très_facile'), 2, 10, 0, 0, true, false, false, true, true, true, true, true, true, true, true, 'Mixer les fruits surgelés avec un peu de lait végétal. Verser dans un bol, garnir de granola, graines et fruits frais.', 'Utiliser des fruits surgelés pour une consistance épaisse', 90, true);

-- MESSAGE DE SUCCÈS
SELECT 'Base de recettes Myko créée avec succès ! 🍽️' as status,
       (SELECT COUNT(*) FROM recipes WHERE is_active = true) || ' recettes actives' as count,
       'Prêt pour l''interface utilisateur !' as next_step;