-- Assertions CI — matérialisation atomique des tâches planifiées.
-- Scénario A : migration hors périmètre, test ignoré.
-- Scénario B : vérifie succès, conversion g→kg, journalisation, idempotence et
-- rollback intégral sur stock insuffisant.

DO $$
DECLARE
  v_exists             boolean;
  v_uid                uuid := '11111111-1111-4111-8111-111111111111';
  v_import_id          bigint;
  v_version_id         uuid;
  v_slot_id            uuid;
  v_task_id            bigint;
  v_prod_id            uuid;
  v_lot_id             uuid;
  v_food_id            bigint;
  v_result             jsonb;
  v_qty                numeric;
  v_count              integer;
  v_failed             boolean := false;
  v_slot2_id           uuid;
  v_task2_id           bigint;
  v_prod2_id           uuid;
BEGIN
  SELECT EXISTS (
    SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.proname = 'set_planned_task_done'
  ) INTO v_exists;

  IF NOT v_exists THEN
    RAISE NOTICE '[atomic-materialization] fonction absente (scénario A hors périmètre — assertions ignorées).';
    RETURN;
  END IF;

  CREATE TABLE IF NOT EXISTS public.nutrition_plan_imports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL
  );

  PERFORM set_config('request.jwt.claim.sub', v_uid::text, true);
  PERFORM set_config('request.jwt.claim.role', 'authenticated', true);
  INSERT INTO auth.users(id) VALUES (v_uid) ON CONFLICT DO NOTHING;

  INSERT INTO public.canonical_foods(canonical_name, density_g_per_ml, unit_weight_grams)
  VALUES ('Farine test atomique', null, null)
  ON CONFLICT (canonical_name) DO UPDATE SET canonical_name = EXCLUDED.canonical_name
  RETURNING id INTO v_food_id;

  INSERT INTO public.nutrition_plan_imports(user_id)
  VALUES (v_uid) RETURNING id INTO v_import_id;

  INSERT INTO public.meal_plan_versions(user_id, import_id, status)
  VALUES (v_uid, v_import_id, 'published') RETURNING id INTO v_version_id;

  INSERT INTO public.meal_plan_slots(
    user_id, plan_version_id, meal_date, meal_type, servings,
    nutrition_total, stock_summary
  ) VALUES (
    v_uid, v_version_id, current_date, 'dejeuner', 2,
    '{"kcal":1000,"proteinG":60,"carbsG":120,"fatG":30,"fiberG":12}'::jsonb,
    '{"allocations":[{"ingredient":"farine"}],"shortages":[]}'::jsonb
  ) RETURNING id INTO v_slot_id;

  INSERT INTO public.nutrition_plan_prep_tasks(
    user_id, import_id, plan_version_id, meal_plan_slot_id,
    task_type, workflow_status, done
  ) VALUES (
    v_uid, v_import_id, v_version_id, v_slot_id,
    'prepare_recipe', 'pending', false
  ) RETURNING id INTO v_task_id;

  INSERT INTO public.planned_productions(
    user_id, plan_version_id, source_task_id, production_key, recipe_code,
    output_name, planned_portions, storage_method, available_from, use_by
  ) VALUES (
    v_uid, v_version_id, v_task_id, 'prod-atomic-ok', 'REC-TEST',
    'Plat atomique', 4, 'refrigerator', current_date, current_date + 3
  ) RETURNING id INTO v_prod_id;

  INSERT INTO public.inventory_lots(
    user_id, canonical_food_id, qty_remaining, initial_qty, unit,
    storage_method, updated_at
  ) VALUES (
    v_uid, v_food_id, 2, 2, 'kg', 'pantry', now()
  ) RETURNING id INTO v_lot_id;

  INSERT INTO public.inventory_reservations(
    user_id, plan_version_id, slot_id, lot_id, ingredient_name,
    reserved_quantity, reserved_unit, status
  ) VALUES (
    v_uid, v_version_id, v_slot_id, v_lot_id, 'Farine', 500, 'g', 'active'
  );

  SELECT public.set_planned_task_done(v_task_id, true) INTO v_result;

  SELECT qty_remaining INTO v_qty FROM public.inventory_lots WHERE id = v_lot_id;
  IF v_qty <> 1.5 THEN
    RAISE EXCEPTION '[atomic-materialization] conversion 500 g → 0,5 kg incorrecte : reste=%', v_qty;
  END IF;

  SELECT count(*) INTO v_count
  FROM public.inventory_movements
  WHERE user_id = v_uid AND lot_id = v_lot_id
    AND movement_type = 'consumption' AND quantity_delta = -0.5;
  IF v_count <> 1 THEN
    RAISE EXCEPTION '[atomic-materialization] mouvement unique -0,5 kg attendu, obtenu %', v_count;
  END IF;

  SELECT count(*) INTO v_count
  FROM public.inventory_reservations
  WHERE lot_id = v_lot_id AND status = 'consumed' AND consumed_at IS NOT NULL;
  IF v_count <> 1 THEN
    RAISE EXCEPTION '[atomic-materialization] réservation non consommée';
  END IF;

  SELECT count(*) INTO v_count
  FROM public.planned_productions pp
  JOIN public.cooked_dishes cd ON cd.id = pp.materialized_cooked_dish_id
  WHERE pp.id = v_prod_id AND pp.status = 'materialized'
    AND cd.portions_remaining = 4
    AND cd.kcal_per_portion = 500
    AND cd.protein_g_per_portion = 30;
  IF v_count <> 1 THEN
    RAISE EXCEPTION '[atomic-materialization] production/plat/nutrition non matérialisés correctement';
  END IF;

  IF NOT (SELECT done FROM public.nutrition_plan_prep_tasks WHERE id = v_task_id) THEN
    RAISE EXCEPTION '[atomic-materialization] tâche non clôturée';
  END IF;

  -- Idempotence : aucune nouvelle sortie ni aucun nouveau plat.
  SELECT public.set_planned_task_done(v_task_id, true) INTO v_result;
  SELECT count(*) INTO v_count FROM public.inventory_movements WHERE user_id = v_uid AND lot_id = v_lot_id;
  IF v_count <> 1 THEN
    RAISE EXCEPTION '[atomic-materialization] seconde validation a dupliqué les mouvements';
  END IF;
  SELECT count(*) INTO v_count FROM public.cooked_dishes WHERE notes LIKE '%prod-atomic-ok%';
  -- Le marqueur contient l'UUID de production, pas la clé : vérifier via FK.
  SELECT count(*) INTO v_count
  FROM public.planned_productions pp
  JOIN public.cooked_dishes cd ON cd.id = pp.materialized_cooked_dish_id
  WHERE pp.id = v_prod_id;
  IF v_count <> 1 THEN
    RAISE EXCEPTION '[atomic-materialization] seconde validation a dupliqué le plat';
  END IF;

  -- Échec atomique : besoin de 3 kg alors que 1,5 kg restent. Toutes les écritures
  -- du sous-bloc doivent être annulées par PostgreSQL.
  INSERT INTO public.meal_plan_slots(
    user_id, plan_version_id, meal_date, meal_type, servings,
    nutrition_total, stock_summary
  ) VALUES (
    v_uid, v_version_id, current_date + 1, 'dejeuner', 2,
    '{"kcal":800,"proteinG":40,"carbsG":100,"fatG":20,"fiberG":10}'::jsonb,
    '{"allocations":[{"ingredient":"farine"}],"shortages":[]}'::jsonb
  ) RETURNING id INTO v_slot2_id;

  INSERT INTO public.nutrition_plan_prep_tasks(
    user_id, import_id, plan_version_id, meal_plan_slot_id,
    task_type, workflow_status, done
  ) VALUES (
    v_uid, v_import_id, v_version_id, v_slot2_id,
    'prepare_recipe', 'pending', false
  ) RETURNING id INTO v_task2_id;

  INSERT INTO public.planned_productions(
    user_id, plan_version_id, source_task_id, production_key, recipe_code,
    output_name, planned_portions, storage_method, available_from, use_by
  ) VALUES (
    v_uid, v_version_id, v_task2_id, 'prod-atomic-fail', 'REC-FAIL',
    'Plat impossible', 2, 'refrigerator', current_date + 1, current_date + 3
  ) RETURNING id INTO v_prod2_id;

  INSERT INTO public.inventory_reservations(
    user_id, plan_version_id, slot_id, lot_id, ingredient_name,
    reserved_quantity, reserved_unit, status
  ) VALUES (
    v_uid, v_version_id, v_slot2_id, v_lot_id, 'Farine', 3000, 'g', 'active'
  );

  BEGIN
    PERFORM public.set_planned_task_done(v_task2_id, true);
  EXCEPTION WHEN OTHERS THEN
    IF position('stock_changed' IN SQLERRM) = 0 THEN RAISE; END IF;
    v_failed := true;
  END;

  IF NOT v_failed THEN
    RAISE EXCEPTION '[atomic-materialization] stock insuffisant aurait dû bloquer';
  END IF;

  SELECT qty_remaining INTO v_qty FROM public.inventory_lots WHERE id = v_lot_id;
  IF v_qty <> 1.5 THEN
    RAISE EXCEPTION '[atomic-materialization] échec non atomique : stock=%', v_qty;
  END IF;
  IF (SELECT done FROM public.nutrition_plan_prep_tasks WHERE id = v_task2_id) THEN
    RAISE EXCEPTION '[atomic-materialization] échec non atomique : tâche clôturée';
  END IF;
  IF EXISTS (SELECT 1 FROM public.planned_productions WHERE id = v_prod2_id AND status <> 'planned') THEN
    RAISE EXCEPTION '[atomic-materialization] échec non atomique : production modifiée';
  END IF;
  IF EXISTS (SELECT 1 FROM public.planned_productions WHERE id = v_prod2_id AND materialized_cooked_dish_id IS NOT NULL) THEN
    RAISE EXCEPTION '[atomic-materialization] échec non atomique : plat créé';
  END IF;

  RAISE NOTICE '[atomic-materialization] succès, conversion, idempotence et rollback passent.';
END $$;
