-- Rollback des valeurs du contrat opérationnel (20260917111000).
--
-- Il remet à NULL les deux colonnes déclaratives sur les lignes que cette
-- migration a visées — 549 formes et 754 recettes.
--
-- CE QU'IL FAUT SAVOIR AVANT DE LE JOUER. Il ne distingue pas ce que CETTE
-- migration a écrit de ce qu'un chargement postérieur aurait écrit : la base ne
-- garde pas cette trace, et prétendre le contraire serait inventer une
-- précision qu'on n'a pas. Rejoué après un chargement de corpus récent, il
-- efface donc aussi les valeurs venues de la chaîne de publication. Elles se
-- rechargent depuis les artefacts versionnés du dépôt — rien n'est perdu pour
-- de bon, mais rien n'est récupérable depuis la base seule.
--
-- ET CE QU'IL COÛTE, MAINTENANT QUE LES RACCORDS JSON SONT PARTIS. Le livrable
-- 0b.4 a retiré de lib/domain/recipes/operationalCatalog.js les deux imports
-- qui comblaient ces colonnes depuis le corpus embarqué. Plus rien ne comble :
-- à colonnes vidées, chaque ingrédient servi vaut 'inconnu' et AUCUN plat n'est
-- végétarien en production — mesuré sur la capture du catalogue servi, 5 297
-- ingrédients « inconnu » sur 346 formes et 0 plat végétarien sur 509. Jouer ce
-- rollback demande donc de remettre les raccords d'abord, ou de recharger les
-- valeurs aussitôt.
--
-- Généré par scripts/db/build-contrat-operationnel-migration.mjs.

WITH origines(cle) AS (
  VALUES
    ('agneau hache cru'),
    ('ail cru'),
    ('ail cru entier'),
    ('ail cru tranche'),
    ('aioli'),
    ('ajwain graines'),
    ('algue gim nori'),
    ('amande'),
    ('amande effilee'),
    ('amande grillee'),
    ('amande mondee'),
    ('ananas frais'),
    ('anchois a l huile egoutte'),
    ('aneth frais'),
    ('anis etoile'),
    ('aonori'),
    ('arachide grillee moulue'),
    ('aubergine africaine fraiche'),
    ('aubergine chinoise fraiche'),
    ('aubergine fraiche'),
    ('aubergine japonaise fraiche'),
    ('aubergine thai fraiche'),
    ('avocat frais'),
    ('baguette vietnamienne'),
    ('baie de genievre'),
    ('banane mure'),
    ('banane plantain mure'),
    ('banane plantain verte'),
    ('bar entier cru vide'),
    ('basilic frais'),
    ('basilic sacre frais'),
    ('basilic thai frais'),
    ('baton de cannelle'),
    ('berbere'),
    ('betterave crue'),
    ('beurre clarifie'),
    ('beurre clarifie epice niter kibbeh'),
    ('beurre clarifie ghee'),
    ('beurre demi sel'),
    ('beurre doux'),
    ('bicarbonate de sodium alimentaire'),
    ('biere blonde'),
    ('biere blonde froide'),
    ('biscuit cuillere'),
    ('blanc d oeuf cru'),
    ('blanc de poulet cru sans peau'),
    ('ble concasse'),
    ('boeuf a braiser cru'),
    ('boeuf a braiser cru en petits cubes'),
    ('boeuf a griller cru en cubes'),
    ('boeuf a griller cru en fines lamelles'),
    ('boeuf cru finement tranche'),
    ('boeuf cru tres finement tranche'),
    ('boeuf cuit effiloche'),
    ('boeuf hache au couteau'),
    ('boeuf hache cru'),
    ('boeuf hache cru 15 mg'),
    ('boeuf marine bulgogi cuit'),
    ('boeuf persille cru tres fin'),
    ('boudin noir a cuire'),
    ('bouillon d agneau'),
    ('bouillon d agneau non sale'),
    ('bouillon d anchois'),
    ('bouillon d anchois et algue'),
    ('bouillon de boeuf'),
    ('bouillon de boeuf non sale'),
    ('bouillon de crevette'),
    ('bouillon de legumes'),
    ('bouillon de legumes non sale'),
    ('bouillon de porc et poulet'),
    ('bouillon de poulet'),
    ('bouillon de veau non sale'),
    ('bouillon de volaille'),
    ('bouillon de volaille clair'),
    ('bouillon de volaille non sale'),
    ('boulgour fin cru'),
    ('bouquet garni frais'),
    ('brocoli cru'),
    ('bucatini secs'),
    ('cacahuete grillee'),
    ('cacao non sucre'),
    ('cafe expresso refroidi'),
    ('cafe moulu'),
    ('calamar cru nettoye'),
    ('calvados'),
    ('cannelle cassia'),
    ('cannelle en baton'),
    ('cannelle moulue'),
    ('capre au vinaigre'),
    ('capre au vinaigre egouttee'),
    ('cardamome noire'),
    ('cardamome verte'),
    ('carotte crue'),
    ('carotte nouvelle crue'),
    ('carvi en graines'),
    ('cassonade'),
    ('celeri branche cru'),
    ('cepe cru'),
    ('cerfeuil frais'),
    ('cerise fraiche denoyautee'),
    ('chair de brochet crue'),
    ('champignon de paille'),
    ('champignon de paris frais'),
    ('champignon seche'),
    ('chana masala'),
    ('chapelure de ble'),
    ('chapelure fine de ble'),
    ('chashu de porc'),
    ('chataigne d eau'),
    ('chicharron de porc'),
    ('chocolat noir 70'),
    ('chocolat noir mexicain'),
    ('chorizo asturien'),
    ('chorizo criollo'),
    ('chou blanc blanchi'),
    ('chou blanc fermente curtido'),
    ('chou blanc frais'),
    ('chou chinois frais'),
    ('chou chinois sale'),
    ('chou emince frais'),
    ('chou kale frais'),
    ('chou kale portugais'),
    ('chou noir kale'),
    ('chou rouge cru'),
    ('chou vert frais'),
    ('chou fleur frais'),
    ('choucroute crue fermentee'),
    ('chourico portugais'),
    ('chutney d abricot'),
    ('ciboule fraiche'),
    ('ciboulette chinoise fraiche'),
    ('ciboulette fraiche'),
    ('cidre brut'),
    ('cinq epices chinoises'),
    ('citron confit au sel'),
    ('citron jaune frais'),
    ('citron vert frais'),
    ('citronnelle fraiche'),
    ('clou de girofle'),
    ('clou de girofle moulu'),
    ('cognac'),
    ('comte'),
    ('concentre de tomate'),
    ('concombre frais'),
    ('confit de canard cuit'),
    ('confit de canard cuit effiloche'),
    ('congre cru'),
    ('coriandre en graines'),
    ('coriandre fraiche'),
    ('coriandre moulue'),
    ('cornichon au vinaigre'),
    ('courge fraiche'),
    ('courgette fraiche'),
    ('creme aigre'),
    ('creme fraiche epaisse'),
    ('creme fraiche liquide entiere'),
    ('creme mexicaine'),
    ('crevette crue decortiquee'),
    ('crevette crue entiere'),
    ('crevette crue surgelee'),
    ('cuisse de poulet crue avec os avec peau'),
    ('cuisse de poulet crue avec os sans peau'),
    ('cumin en graines'),
    ('cumin moulu'),
    ('curcuma moulu'),
    ('curry en poudre'),
    ('dashi'),
    ('doenjang pate de soja fermentee'),
    ('dos de cabillaud cru'),
    ('doubanjiang'),
    ('douchi haricot noir fermente'),
    ('eau'),
    ('eau chaude'),
    ('eau de coco'),
    ('eau glacee'),
    ('eau glacee gazeuse'),
    ('echalote crue'),
    ('echine de porc crue'),
    ('emmental rape'),
    ('endive fraiche'),
    ('eomuk gateau de poisson'),
    ('epaule d agneau crue'),
    ('epaule de porc crue'),
    ('epaule de veau crue'),
    ('epaule de veau crue en cubes'),
    ('epinard frais'),
    ('epinard surgele'),
    ('escalope de dinde crue'),
    ('escalope de veau crue fine'),
    ('estragon frais'),
    ('farine de ble t55'),
    ('farine de ble type 00'),
    ('farine de mais blanche'),
    ('farine de pois chiche'),
    ('farine de pois chiche grillee'),
    ('farine de sarrasin'),
    ('fecule de mais'),
    ('fenouil frais'),
    ('fenugrec en graines'),
    ('fenugrec seche kasuri methi'),
    ('feta'),
    ('feuille de brick'),
    ('feuille de combava'),
    ('feuille de curry fraiche'),
    ('feuille de lasagne seche'),
    ('feuille de laurier sechee'),
    ('feuille de sauge fraiche'),
    ('feuille de vigne en saumure'),
    ('feve a ecosser fraiche'),
    ('filet de boeuf cru en lanieres'),
    ('filet de merlu surgele'),
    ('filet mignon de porc cru'),
    ('flanchet de boeuf cru'),
    ('foie gras de canard cru'),
    ('frisee fraiche'),
    ('fromage blanc a 3 pourcent'),
    ('fromage de chevre buche'),
    ('fromage fondu en portions'),
    ('fromage frais mexicain'),
    ('fruits de mer cuits surgeles'),
    ('fumet de poisson'),
    ('galanga frais'),
    ('garam masala'),
    ('gateau de riz coreen tteok'),
    ('gelatine feuille'),
    ('gesier de canard confit'),
    ('ghee'),
    ('gigot d agneau cru'),
    ('gingembre frais'),
    ('gingembre marine rouge'),
    ('gingembre moulu'),
    ('gnocchi de pomme de terre frais'),
    ('gochugaru'),
    ('gochujang'),
    ('gousse de vanille'),
    ('graine de moutarde'),
    ('graisse d oie'),
    ('gruyere rape'),
    ('guanciale cru'),
    ('haricot blanc cuit egoutte'),
    ('haricot blanc sec'),
    ('haricot cornille sec'),
    ('haricot flageolet appertise egoutte'),
    ('haricot flageolet sec'),
    ('haricot geant sec'),
    ('haricot kilometre cru'),
    ('haricot lingot sec'),
    ('haricot noir sec'),
    ('haricot rouge cuit egoutte'),
    ('haricot rouge sec'),
    ('haricot vert cru'),
    ('haricot vert cuit'),
    ('harissa'),
    ('haut de cuisse de poulet cru desosse'),
    ('haut de cuisse de poulet cru desosse sans peau'),
    ('herbes de provence sechees'),
    ('huile d arachide'),
    ('huile d olive vierge extra'),
    ('huile de colza raffinee'),
    ('huile de dende'),
    ('huile de friture'),
    ('huile de moutarde'),
    ('huile de noix'),
    ('huile de palme rouge'),
    ('huile de sesame grille'),
    ('huile pimentee'),
    ('huile pimentee au roucou'),
    ('huile vegetale'),
    ('huile vegetale raffinee'),
    ('jaggery'),
    ('jambon blanc cuit'),
    ('jambon de bayonne'),
    ('jambon serrano'),
    ('jambonneau cuit'),
    ('jarret de boeuf cru'),
    ('jarret de boeuf cru avec os'),
    ('jarret de veau cru en tranches avec os'),
    ('jaune d oeuf cru'),
    ('jaune d oeuf cuit'),
    ('jus d orange amere'),
    ('jus de citron frais'),
    ('jus de citron vert frais'),
    ('jus de tomate'),
    ('kecap manis'),
    ('kimchi de chou fermente mur'),
    ('lait de coco'),
    ('lait demi ecreme'),
    ('lait entier'),
    ('lait evapore'),
    ('laitue fraiche'),
    ('langue de boeuf crue'),
    ('lapin cru decoupe'),
    ('lardon fume cru'),
    ('lentille brune seche crue'),
    ('lentille corail seche crue'),
    ('lentille urad blanche seche'),
    ('lentille urad noire entiere seche'),
    ('lentille verte seche crue'),
    ('levure boulangere fraiche'),
    ('levure boulangere seche'),
    ('levure chimique'),
    ('lieu noir surgele'),
    ('linguica portugaise'),
    ('magret de canard fume'),
    ('marsala'),
    ('masa harina'),
    ('mascarpone'),
    ('mayonnaise'),
    ('mayonnaise japonaise'),
    ('melasse de grenade'),
    ('menthe fraiche'),
    ('menthe sechee'),
    ('merguez crue'),
    ('miel'),
    ('mimolette demi vieille'),
    ('mirin'),
    ('morcilla asturienne'),
    ('morille crue'),
    ('morue salee seche'),
    ('moule commune crue'),
    ('moutarde de dijon'),
    ('mozzarella'),
    ('muscade moulue'),
    ('navet cru'),
    ('noisette grillee'),
    ('noix'),
    ('noix de saint jacques crue'),
    ('nouille de ble chinoise seche'),
    ('nouille de riz plate seche'),
    ('nouille ramen fraiche'),
    ('oeuf cru'),
    ('oeuf dur'),
    ('oeuf marine ajitama'),
    ('oignon blanc cru'),
    ('oignon en poudre'),
    ('oignon grelot cru'),
    ('oignon jaune cru'),
    ('oignon nouveau frais'),
    ('oignon rouge cru'),
    ('olive noire'),
    ('olive noire denoyautee'),
    ('olive verte denoyautee'),
    ('orange fraiche'),
    ('origan mexicain seche'),
    ('origan seche'),
    ('os a moelle de boeuf'),
    ('oseille crue'),
    ('pain blanc rassis'),
    ('pain d epices'),
    ('pain de campagne'),
    ('pain de mie'),
    ('pain pav'),
    ('pain pita'),
    ('pain rassis'),
    ('pain toscan rassis'),
    ('paleron de boeuf cru'),
    ('paleron de boeuf cru pare'),
    ('paneer'),
    ('panko'),
    ('papaye verte'),
    ('paprika doux'),
    ('paprika doux hongrois'),
    ('paprika fort hongrois'),
    ('paprika fume'),
    ('parmesan affine'),
    ('patate douce crue'),
    ('patate douce crue epluchee'),
    ('pate brisee crue'),
    ('pate d arachide pure'),
    ('pate feuilletee crue'),
    ('pate sablee crue'),
    ('pates fraiches aux oeufs crues'),
    ('pates seches courtes'),
    ('pave de saumon cru sans peau'),
    ('pecorino romano'),
    ('persil frais'),
    ('persil plat frais'),
    ('petit pois surgele'),
    ('petites pates seches'),
    ('pied de porc cru'),
    ('pignon de pin'),
    ('piment ancho seche'),
    ('piment d espelette moulu'),
    ('piment de cayenne'),
    ('piment de la jamaique en grains'),
    ('piment de la jamaique moulu'),
    ('piment doux vert frais'),
    ('piment du cachemire moulu'),
    ('piment en poudre'),
    ('piment frais'),
    ('piment guajillo seche'),
    ('piment habanero'),
    ('piment jalapeno frais'),
    ('piment oiseau frais'),
    ('piment pasilla seche'),
    ('piment rouge frais'),
    ('piment rouge seche'),
    ('piment scotch bonnet'),
    ('piment seche'),
    ('piment serrano'),
    ('piment vert doux frais'),
    ('piment vert frais'),
    ('poire asiatique fraiche'),
    ('poire fraiche'),
    ('poireau cru'),
    ('pois chiche cuit egoutte'),
    ('pois chiche sec cru'),
    ('poitrine de porc crue'),
    ('poitrine de porc crue avec couenne'),
    ('poitrine de porc crue fine'),
    ('poitrine de porc demi sel'),
    ('poitrine de porc fumee'),
    ('poivre blanc moulu'),
    ('poivre du sichuan'),
    ('poivre noir en grains'),
    ('poivre noir moulu'),
    ('poivron jaune frais'),
    ('poivron rouge frais'),
    ('poivron vert frais'),
    ('pomme de terre crue avec peau'),
    ('pomme de terre crue epluchee'),
    ('pomme de terre cuite'),
    ('pomme de terre nouvelle crue'),
    ('pomme fraiche'),
    ('porc hache cru'),
    ('potimarron frais epepine'),
    ('poule crue'),
    ('poulet cuit effiloche'),
    ('poulet entier cru'),
    ('poulet entier cru en morceaux'),
    ('poulet entier cru pret a cuire'),
    ('poulpe cuit'),
    ('pousse de bambou'),
    ('pousse de soja fraiche'),
    ('pruneau denoyaute'),
    ('pul biber'),
    ('quenelle nature crue'),
    ('quesillo oaxaca'),
    ('quinoa cru'),
    ('radis daikon cru'),
    ('radis frais'),
    ('raisin sec'),
    ('ras el hanout'),
    ('reblochon au lait cru'),
    ('rhum ambre'),
    ('riz arborio cru'),
    ('riz basmati cru'),
    ('riz bomba cru'),
    ('riz brise cru'),
    ('riz complet cru'),
    ('riz cru'),
    ('riz etuve cru'),
    ('riz japonais cru'),
    ('riz jasmin cru'),
    ('riz long blanc cru'),
    ('riz rond blanc cru'),
    ('riz rond coreen cru'),
    ('riz rond cru'),
    ('romarin frais'),
    ('rouget grondin cru'),
    ('safran'),
    ('saindoux'),
    ('saint pierre cru'),
    ('sake'),
    ('sake de cuisine'),
    ('salsa roja'),
    ('salsa verde'),
    ('sambal'),
    ('sambar powder'),
    ('sauce hoisin'),
    ('sauce huitre'),
    ('sauce poisson'),
    ('sauce soja'),
    ('sauce soja claire'),
    ('sauce soja coreenne'),
    ('sauce soja foncee'),
    ('sauce soja japonaise'),
    ('sauce soja legere'),
    ('sauce soja legere speciale poisson'),
    ('sauce soja philippine'),
    ('sauce worcestershire'),
    ('sauce yakisoba'),
    ('saucisse chinoise lap cheong'),
    ('saucisse de montbeliard'),
    ('saucisse de morteau'),
    ('saucisse de toulouse crue'),
    ('saucisse vegetale au tofu'),
    ('saumure legere'),
    ('seitan'),
    ('sel fin'),
    ('semoule de ble dur moyenne seche'),
    ('sesame'),
    ('sesame grille'),
    ('shiitake frais'),
    ('shiitake seche'),
    ('spaghetti secs'),
    ('ssamjang'),
    ('sucre brun'),
    ('sucre candi'),
    ('sucre de palme'),
    ('sucre semoule'),
    ('sumac moulu'),
    ('tahini'),
    ('tamarin en pate'),
    ('tare de soja'),
    ('thon au naturel en conserve egoutte'),
    ('thym frais'),
    ('thym seche'),
    ('tofu ferme'),
    ('tofu fume'),
    ('tofu soyeux ferme'),
    ('tomate cerise fraiche'),
    ('tomate concassee en conserve'),
    ('tomate concentree'),
    ('tomate entiere pelee en conserve'),
    ('tomate fraiche mure'),
    ('tomate rapee'),
    ('tomatillo frais'),
    ('tome fraiche de l aubrac'),
    ('tonnarelli secs'),
    ('tortilla de ble'),
    ('tortilla de mais'),
    ('truite crue'),
    ('truite fumee'),
    ('vanille liquide'),
    ('vermicelle fin sec'),
    ('vermouth sec'),
    ('vin blanc sec'),
    ('vin blanc sec d alsace'),
    ('vin de riz taiwanais'),
    ('vin rouge de bourgogne'),
    ('vin rouge sec'),
    ('vin shaoxing'),
    ('vinaigre balsamique'),
    ('vinaigre blanc'),
    ('vinaigre de canne'),
    ('vinaigre de cidre'),
    ('vinaigre de malt'),
    ('vinaigre de palmier ou cidre'),
    ('vinaigre de riz'),
    ('vinaigre de vin rouge'),
    ('vinaigre de xeres'),
    ('vinaigre noir chinois'),
    ('whisky'),
    ('yaourt a la grecque'),
    ('yaourt grec'),
    ('yaourt nature'),
    ('zakwas de betterave fermente'),
    ('zeste de citron')
)
UPDATE catalog.food_forms ff
SET origin = NULL, origin_source = NULL, updated_at = now()
FROM origines
WHERE ff.canonical_name_normalized = origines.cle
  AND (ff.origin IS NOT NULL OR ff.origin_source IS NOT NULL);

WITH profils(code) AS (
  VALUES
    ('FR-001'),
    ('FR-002'),
    ('FR-003'),
    ('FR-004'),
    ('IT-001'),
    ('FR-005'),
    ('FR-006'),
    ('FR-008'),
    ('FR-009'),
    ('MAG-001'),
    ('MX-001'),
    ('FR-010'),
    ('FR-011'),
    ('VEG-001'),
    ('VEG-002'),
    ('EGG-001'),
    ('VEG-003'),
    ('IND-001'),
    ('IND-002'),
    ('MED-001'),
    ('LEV-001'),
    ('LEV-002'),
    ('IT-002'),
    ('IT-003'),
    ('IT-004'),
    ('IT-005'),
    ('IT-006'),
    ('IT-007'),
    ('FR-012'),
    ('FR-013'),
    ('FR-014'),
    ('IT-008'),
    ('FR-015'),
    ('FR-016'),
    ('FR-017'),
    ('FR-018'),
    ('FR-019'),
    ('GR-001'),
    ('FR-020'),
    ('FR-021'),
    ('FR-022'),
    ('FR-023'),
    ('DESS-001'),
    ('DESS-002'),
    ('DESS-003'),
    ('DESS-004'),
    ('DESS-005'),
    ('DESS-006'),
    ('DESS-007'),
    ('DESS-008'),
    ('FR-024'),
    ('FR-025'),
    ('FR-026'),
    ('FR-027'),
    ('FR-028'),
    ('DESS-009'),
    ('DESS-010'),
    ('DESS-011'),
    ('FR-029'),
    ('FR-030'),
    ('FR-031'),
    ('FR-032'),
    ('FR-033'),
    ('FR-034'),
    ('FR-035'),
    ('FR-036'),
    ('FR-037'),
    ('FR-038'),
    ('FR-039'),
    ('DESS-012'),
    ('FR-040'),
    ('REAL-073'),
    ('REAL-074'),
    ('REAL-075'),
    ('REAL-076'),
    ('REAL-077'),
    ('REAL-078'),
    ('REAL-079'),
    ('REAL-080'),
    ('REAL-081'),
    ('REAL-082'),
    ('REAL-083'),
    ('REAL-084'),
    ('REAL-085'),
    ('REAL-086'),
    ('REAL-087'),
    ('REAL-088'),
    ('REAL-089'),
    ('REAL-090'),
    ('REAL-091'),
    ('REAL-092'),
    ('REAL-093'),
    ('REAL-094'),
    ('REAL-095'),
    ('REAL-096'),
    ('REAL-097'),
    ('REAL-098'),
    ('REAL-099'),
    ('REAL-100'),
    ('REAL-101'),
    ('REAL-102'),
    ('REAL-103'),
    ('REAL-104'),
    ('REAL-105'),
    ('REAL-106'),
    ('REAL-107'),
    ('REAL-108'),
    ('REAL-109'),
    ('REAL-110'),
    ('REAL-111'),
    ('REAL-112'),
    ('REAL-113'),
    ('REAL-114'),
    ('REAL-115'),
    ('REAL-116'),
    ('REAL-117'),
    ('REAL-118'),
    ('REAL-119'),
    ('REAL-120'),
    ('REAL-121'),
    ('REAL-122'),
    ('REAL-123'),
    ('REAL-124'),
    ('REAL-125'),
    ('REAL-126'),
    ('REAL-127'),
    ('REAL-128'),
    ('REAL-129'),
    ('REAL-130'),
    ('REAL-131'),
    ('REAL-132'),
    ('REAL-133'),
    ('REAL-134'),
    ('REAL-135'),
    ('REAL-136'),
    ('REAL-137'),
    ('REAL-138'),
    ('REAL-139'),
    ('REAL-140'),
    ('REAL-141'),
    ('REAL-142'),
    ('REAL-143'),
    ('REAL-144'),
    ('REAL-145'),
    ('REAL-146'),
    ('REAL-147'),
    ('REAL-148'),
    ('REAL-149'),
    ('REAL-150'),
    ('REAL-151'),
    ('REAL-152'),
    ('REAL-153'),
    ('REAL-154'),
    ('REAL-155'),
    ('REAL-156'),
    ('REAL-157'),
    ('REAL-158'),
    ('REAL-159'),
    ('REAL-160'),
    ('REAL-161'),
    ('REAL-162'),
    ('REAL-163'),
    ('REAL-164'),
    ('REAL-165'),
    ('REAL-166'),
    ('REAL-167'),
    ('REAL-168'),
    ('REAL-169'),
    ('REAL-170'),
    ('REAL-171'),
    ('REAL-172'),
    ('REAL-173'),
    ('REAL-174'),
    ('REAL-175'),
    ('REAL-176'),
    ('REAL-177'),
    ('REAL-178'),
    ('REAL-179'),
    ('REAL-180'),
    ('REAL-181'),
    ('REAL-182'),
    ('REAL-183'),
    ('REAL-184'),
    ('REAL-185'),
    ('REAL-186'),
    ('REAL-187'),
    ('REAL-188'),
    ('REAL-189'),
    ('REAL-190'),
    ('REAL-191'),
    ('REAL-192'),
    ('REAL-193'),
    ('REAL-194'),
    ('REAL-195'),
    ('REAL-196'),
    ('REAL-197'),
    ('REAL-198'),
    ('REAL-199'),
    ('REAL-200'),
    ('REAL-201'),
    ('REAL-202'),
    ('REAL-203'),
    ('REAL-204'),
    ('REAL-205'),
    ('REAL-206'),
    ('REAL-207'),
    ('REAL-208'),
    ('REAL-209'),
    ('REAL-210'),
    ('REAL-211'),
    ('REAL-212'),
    ('REAL-213'),
    ('REAL-214'),
    ('REAL-215'),
    ('REAL-216'),
    ('REAL-217'),
    ('REAL-218'),
    ('REAL-219'),
    ('REAL-220'),
    ('REAL-221'),
    ('REAL-222'),
    ('REAL-223'),
    ('REAL-224'),
    ('REAL-225'),
    ('REAL-226'),
    ('REAL-227'),
    ('REAL-228'),
    ('REAL-229'),
    ('REAL-230'),
    ('REAL-231'),
    ('REAL-232'),
    ('REAL-233'),
    ('REAL-234'),
    ('REAL-235'),
    ('REAL-236'),
    ('REAL-237'),
    ('REAL-238'),
    ('REAL-239'),
    ('REAL-240'),
    ('REAL-241'),
    ('REAL-242'),
    ('REAL-243'),
    ('REAL-244'),
    ('REAL-245'),
    ('REAL-246'),
    ('REAL-247'),
    ('REAL-248'),
    ('REAL-249'),
    ('REAL-250'),
    ('REAL-251'),
    ('REAL-252'),
    ('REAL-253'),
    ('REAL-254'),
    ('REAL-255'),
    ('REAL-256'),
    ('REAL-257'),
    ('REAL-258'),
    ('REAL-259'),
    ('REAL-260'),
    ('REAL-261'),
    ('REAL-262'),
    ('REAL-263'),
    ('REAL-264'),
    ('REAL-265'),
    ('REAL-266'),
    ('REAL-267'),
    ('REAL-268'),
    ('REAL-269'),
    ('REAL-270'),
    ('REAL-271'),
    ('REAL-272'),
    ('REAL-273'),
    ('REAL-274'),
    ('REAL-275'),
    ('REAL-276'),
    ('REAL-277'),
    ('REAL-278'),
    ('REAL-279'),
    ('REAL-280'),
    ('REAL-281'),
    ('REAL-282'),
    ('REAL-283'),
    ('REAL-284'),
    ('REAL-285'),
    ('REAL-286'),
    ('REAL-287'),
    ('REAL-288'),
    ('REAL-289'),
    ('REAL-290'),
    ('REAL-291'),
    ('REAL-292'),
    ('REAL-293'),
    ('REAL-294'),
    ('REAL-295'),
    ('REAL-296'),
    ('REAL-297'),
    ('REAL-298'),
    ('REAL-299'),
    ('REAL-300'),
    ('REAL-301'),
    ('REAL-302'),
    ('PROT-001'),
    ('PROT-002'),
    ('PROT-005'),
    ('PROT-006'),
    ('PROT-007'),
    ('PROT-008'),
    ('PROT-009'),
    ('SRC-001'),
    ('SRC-002'),
    ('SRC-003'),
    ('SRC-004'),
    ('SRC-005'),
    ('SRC-006'),
    ('SRC-007'),
    ('SRC-008'),
    ('SRC-009'),
    ('SRC-010'),
    ('SRC-011'),
    ('SRC-012'),
    ('SRC-013'),
    ('SRC-014'),
    ('SRC-015'),
    ('SRC-016'),
    ('SRC-017'),
    ('SRC-018'),
    ('SRC-019'),
    ('SRC-020'),
    ('SRC-021'),
    ('SRC-022'),
    ('SRC-023'),
    ('SRC-024'),
    ('SRC-025'),
    ('SRC-026'),
    ('SRC-027'),
    ('SRC-028'),
    ('SRC-029'),
    ('SRC-030'),
    ('SRC-031'),
    ('SRC-032'),
    ('SRC-033'),
    ('SRC-034'),
    ('SRC-035'),
    ('SRC-036'),
    ('SRC-037'),
    ('SRC-038'),
    ('SRC-039'),
    ('SRC-040'),
    ('SRC-041'),
    ('SRC-042'),
    ('SRC-043'),
    ('SRC-044'),
    ('SRC-045'),
    ('SRC-046'),
    ('SRC-047'),
    ('SRC-048'),
    ('SRC-049'),
    ('SRC-050'),
    ('SRC-051'),
    ('SRC-052'),
    ('SRC-053'),
    ('SRC-054'),
    ('SRC-055'),
    ('SRC-056'),
    ('SRC-057'),
    ('SRC-058'),
    ('SRC-059'),
    ('SRC-060'),
    ('SRC-001-D1'),
    ('SRC-001-D2'),
    ('SRC-003-D1'),
    ('SRC-004-D1'),
    ('SRC-004-D2'),
    ('SRC-005-D1'),
    ('SRC-005-D2'),
    ('SRC-006-D1'),
    ('SRC-006-D2'),
    ('SRC-008-D1'),
    ('SRC-008-D2'),
    ('SRC-008-D3'),
    ('SRC-008-D4'),
    ('SRC-011-D1'),
    ('SRC-011-D2'),
    ('SRC-012-D1'),
    ('SRC-012-D2'),
    ('SRC-012-D3'),
    ('SRC-012-D4'),
    ('SRC-014-D1'),
    ('SRC-014-D2'),
    ('SRC-014-D3'),
    ('SRC-015-D1'),
    ('SRC-015-D2'),
    ('SRC-018-D1'),
    ('SRC-018-D2'),
    ('SRC-002-D1'),
    ('SRC-009-D1'),
    ('SRC-009-D2'),
    ('SRC-009-D3'),
    ('SRC-010-D1'),
    ('SRC-010-D2'),
    ('SRC-010-D3'),
    ('SRC-010-D4'),
    ('SRC-007-D1'),
    ('SRC-007-D2'),
    ('SRC-007-D3'),
    ('SRC-013-D1'),
    ('SRC-013-D2'),
    ('SRC-013-D3'),
    ('SRC-015-D3'),
    ('SRC-015-D4'),
    ('SRC-014-D4'),
    ('SRC-016-D1'),
    ('SRC-016-D2'),
    ('SRC-016-D3'),
    ('SRC-016-D4'),
    ('SRC-017-D1'),
    ('SRC-017-D2'),
    ('SRC-017-D3'),
    ('SRC-018-D3'),
    ('SRC-019-D1'),
    ('SRC-019-D2'),
    ('SRC-019-D3'),
    ('SRC-019-D4'),
    ('SRC-020-D1'),
    ('SRC-020-D2'),
    ('SRC-020-D3'),
    ('SRC-020-D4'),
    ('SRC-021-D1'),
    ('SRC-021-D2'),
    ('SRC-021-D3'),
    ('SRC-021-D4'),
    ('SRC-022-D1'),
    ('SRC-022-D2'),
    ('SRC-022-D3'),
    ('SRC-022-D4'),
    ('SRC-023-D1'),
    ('SRC-023-D2'),
    ('SRC-023-D3'),
    ('SRC-023-D4'),
    ('SRC-024-D1'),
    ('SRC-025-D1'),
    ('SRC-025-D2'),
    ('SRC-025-D3'),
    ('SRC-025-D4'),
    ('SRC-026-D1'),
    ('SRC-026-D2'),
    ('SRC-027-D1'),
    ('SRC-027-D2'),
    ('SRC-027-D3'),
    ('SRC-027-D4'),
    ('SRC-028-D1'),
    ('SRC-029-D1'),
    ('SRC-029-D2'),
    ('SRC-029-D3'),
    ('SRC-029-D4'),
    ('SRC-029-D5'),
    ('SRC-031-D1'),
    ('SRC-031-D2'),
    ('SRC-031-D3'),
    ('SRC-031-D4'),
    ('SRC-032-D1'),
    ('SRC-032-D2'),
    ('SRC-032-D3'),
    ('SRC-032-D4'),
    ('SRC-032-D5'),
    ('SRC-032-D6'),
    ('SRC-033-D1'),
    ('SRC-033-D2'),
    ('SRC-033-D3'),
    ('SRC-034-D1'),
    ('SRC-035-D1'),
    ('SRC-035-D2'),
    ('SRC-035-D3'),
    ('SRC-036-D1'),
    ('SRC-036-D2'),
    ('SRC-036-D3'),
    ('SRC-036-D4'),
    ('SRC-037-D1'),
    ('SRC-037-D2'),
    ('SRC-037-D3'),
    ('SRC-038-D1'),
    ('SRC-038-D2'),
    ('SRC-038-D3'),
    ('SRC-038-D4'),
    ('SRC-039-D1'),
    ('SRC-039-D2'),
    ('SRC-040-D1'),
    ('SRC-040-D2'),
    ('SRC-040-D3'),
    ('SRC-041-D1'),
    ('SRC-041-D2'),
    ('SRC-041-D3'),
    ('SRC-041-D4'),
    ('SRC-042-D1'),
    ('SRC-042-D2'),
    ('SRC-042-D3'),
    ('SRC-043-D1'),
    ('SRC-043-D2'),
    ('SRC-044-D1'),
    ('SRC-044-D2'),
    ('SRC-044-D3'),
    ('SRC-045-D1'),
    ('SRC-045-D2'),
    ('SRC-045-D3'),
    ('SRC-045-D4'),
    ('SRC-046-D1'),
    ('SRC-046-D2'),
    ('SRC-046-D3'),
    ('SRC-047-D1'),
    ('SRC-047-D2'),
    ('SRC-047-D3'),
    ('SRC-047-D4'),
    ('SRC-048-D1'),
    ('SRC-048-D2'),
    ('SRC-048-D3'),
    ('SRC-048-D4'),
    ('SRC-049-D1'),
    ('SRC-050-D1'),
    ('SRC-050-D2'),
    ('SRC-051-D1'),
    ('SRC-051-D2'),
    ('SRC-051-D3'),
    ('SRC-051-D4'),
    ('SRC-052-D1'),
    ('SRC-052-D2'),
    ('SRC-052-D3'),
    ('SRC-052-D4'),
    ('SRC-053-D1'),
    ('SRC-053-D2'),
    ('SRC-053-D3'),
    ('SRC-054-D1'),
    ('SRC-054-D2'),
    ('SRC-056-D1'),
    ('SRC-056-D2'),
    ('SRC-056-D3'),
    ('SRC-057-D1'),
    ('SRC-057-D2'),
    ('SRC-057-D3'),
    ('SRC-057-D4'),
    ('SRC-058-D1'),
    ('SRC-058-D2'),
    ('SRC-058-D3'),
    ('SRC-058-D4'),
    ('SRC-059-D1'),
    ('SRC-059-D2'),
    ('SRC-059-D3'),
    ('SRC-060-D1'),
    ('SRC-060-D2'),
    ('SRC-060-D3'),
    ('SRC-060-D4'),
    ('SRC-003-D2'),
    ('SRC-009-D4'),
    ('SRC-014-D5'),
    ('SRC-014-D6'),
    ('SRC-017-D4'),
    ('SRC-024-D2'),
    ('SRC-026-D3'),
    ('SRC-034-D2'),
    ('SRC-034-D3'),
    ('SRC-039-D3'),
    ('SRC-039-D4'),
    ('SRC-039-D5'),
    ('SRC-040-D4'),
    ('SRC-049-D2'),
    ('SRC-049-D3'),
    ('SRC-050-D3'),
    ('SRC-050-D4'),
    ('SRC-053-D4'),
    ('SRC-053-D5'),
    ('SRC-054-D3'),
    ('SRC-054-D4'),
    ('SRC-054-D5'),
    ('SRC-055-D1'),
    ('SRC-055-D2'),
    ('SRC-056-D4'),
    ('SRC-056-D5'),
    ('IT-007-D1'),
    ('IT-007-D2'),
    ('IT-001-D1'),
    ('IT-001-D3'),
    ('IT-004-D1'),
    ('IT-004-D2'),
    ('IT-008-D1'),
    ('IT-008-D2'),
    ('MX-001-D1'),
    ('MX-001-D2'),
    ('VEG-001-D1'),
    ('VEG-001-D2'),
    ('VEG-001-D3'),
    ('RAP-001'),
    ('RAP-002'),
    ('RAP-003'),
    ('RAP-004'),
    ('RAP-005'),
    ('RAP-006'),
    ('RAP-007'),
    ('RAP-008'),
    ('RAP-009'),
    ('RAP-010'),
    ('RAP-011'),
    ('RAP-012'),
    ('RAP-013'),
    ('RAP-014'),
    ('RAP-015'),
    ('RAP-016'),
    ('RAP-017'),
    ('RAP-018'),
    ('RAP-019'),
    ('RAP-020'),
    ('RAP-021'),
    ('RAP-022'),
    ('RAP-023'),
    ('RAP-024'),
    ('RAP-025'),
    ('RAP-026'),
    ('RAP-027'),
    ('RAP-028'),
    ('RAP-029'),
    ('RAP-030'),
    ('RAP-031'),
    ('RAP-032'),
    ('RAP-033'),
    ('RAP-034'),
    ('RAP-035'),
    ('RAP-036'),
    ('RAP-037'),
    ('RAP-038'),
    ('RAP-039'),
    ('RAP-040'),
    ('RAP-041'),
    ('RAP-042'),
    ('RAP-043'),
    ('RAP-044'),
    ('RAP-045'),
    ('RAP-046'),
    ('RAP-047'),
    ('RAP-048'),
    ('RAP-049'),
    ('RAP-050'),
    ('RAP-051'),
    ('RAP-052'),
    ('VAR-001'),
    ('VAR-002'),
    ('VAR-003'),
    ('VAR-004'),
    ('VAR-005'),
    ('VAR-006'),
    ('VAR-009'),
    ('VAR-011'),
    ('VAR-012'),
    ('VAR-013'),
    ('VAR-014'),
    ('VAR-015'),
    ('VAR-016'),
    ('VAR-017'),
    ('VAR-018'),
    ('VAR-019'),
    ('VAR-020'),
    ('VAR-021'),
    ('VAR-022'),
    ('VAR-023'),
    ('VAR-024'),
    ('VAR-025'),
    ('VAR-026'),
    ('VAR-027'),
    ('VAR-028'),
    ('VAR-029'),
    ('VAR-030'),
    ('VAR-031'),
    ('VAR-032'),
    ('VAR-033'),
    ('VAR-034'),
    ('VAR-035'),
    ('VAR-036'),
    ('VAR-037'),
    ('VAR-038'),
    ('VAR-039'),
    ('VAR-040'),
    ('VAR-041'),
    ('VAR-042'),
    ('VAR-043'),
    ('VAR-044'),
    ('VAR-045'),
    ('DEN-001'),
    ('DEN-002'),
    ('DEN-003'),
    ('DEN-004'),
    ('DEN-005'),
    ('DEN-006'),
    ('DEN-007'),
    ('DEN-008'),
    ('DEN-009'),
    ('DEN-010'),
    ('DEN-011'),
    ('DEN-012'),
    ('DEN-013'),
    ('DEN-014'),
    ('DEN-015'),
    ('DEN-016'),
    ('DEN-017'),
    ('DEN-018'),
    ('DEN-019'),
    ('DEN-020'),
    ('DEN-021'),
    ('DEN-022'),
    ('DEN-023'),
    ('JUM-001'),
    ('JUM-002'),
    ('JUM-003'),
    ('JUM-004'),
    ('JUM-005'),
    ('JUM-006'),
    ('JUM-007'),
    ('JUM-031'),
    ('JUM-032'),
    ('JUM-033'),
    ('JUM-041'),
    ('JUM-042'),
    ('JUM-043'),
    ('JUM-051'),
    ('JUM-052'),
    ('JUM-053'),
    ('JUM-054'),
    ('JUM-055'),
    ('JUM-061'),
    ('JUM-062'),
    ('JUM-063'),
    ('JUM-064'),
    ('JUM-065'),
    ('JUM-071'),
    ('JUM-072'),
    ('JUM-073'),
    ('JUM-074'),
    ('JUM-081'),
    ('JUM-082'),
    ('JUM-083'),
    ('JUM-084'),
    ('JUM-091'),
    ('JUM-092'),
    ('JUM-093'),
    ('JUM-094'),
    ('JUM-095'),
    ('JUM-101'),
    ('JUM-102'),
    ('JUM-103'),
    ('JUM-104'),
    ('JUM-111'),
    ('JUM-112'),
    ('JUM-113'),
    ('JUM-114'),
    ('JUM-115'),
    ('JUM-121'),
    ('JUM-122'),
    ('JUM-123')
)
UPDATE culinary.recipe_versions rv
SET conservation_profile = NULL
FROM profils, ops.source_datasets ds
WHERE ds.id = rv.source_dataset_id
  AND ds.code = 'myko_editorial_v3'
  AND upper(rv.source_record_key) = profils.code
  AND rv.conservation_profile IS NOT NULL;
