-- ============================================================================
-- Conservation sûre, traçable et sans fallback silencieux
-- ============================================================================
-- 1. Les politiques distinguent explicitement interdit / inconnu / autorisé.
-- 2. Les lots conservent la provenance de la décision et de leur date.
-- 3. Les volailles crues sont interdites au garde-manger.
-- 4. Les lots de volaille déjà mal classés sont sécurisés et signalés à revoir.
--
-- Migration additive et idempotente. Les règles globales sont en lecture seule
-- via la Data API ; seuls les migrations/administrateurs peuvent les modifier.

CREATE TABLE IF NOT EXISTS public.food_storage_policies (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canonical_food_id   bigint REFERENCES public.canonical_foods(id) ON DELETE CASCADE,
  archetype_id        bigint REFERENCES public.archetypes(id) ON DELETE CASCADE,
  food_state          text NOT NULL DEFAULT 'any',
  purchase_state      text NOT NULL DEFAULT 'any',
  storage_method      text NOT NULL,
  suitability         text NOT NULL,
  duration_days       integer,
  expiry_kind         text NOT NULL DEFAULT 'estimate',
  min_temperature_c   numeric,
  max_temperature_c   numeric,
  source_type         text NOT NULL,
  source_ref          text,
  confidence          numeric NOT NULL,
  policy_version      text NOT NULL,
  reason              text,
  verified_at         timestamptz NOT NULL DEFAULT now(),
  active              boolean NOT NULL DEFAULT true,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT food_storage_policies_one_entity
    CHECK (num_nonnulls(canonical_food_id, archetype_id) = 1),
  CONSTRAINT food_storage_policies_food_state
    CHECK (food_state IN ('any', 'raw', 'cooked', 'opened', 'thawed')),
  CONSTRAINT food_storage_policies_purchase_state
    CHECK (purchase_state IN ('any', 'unknown', 'ambient', 'chilled', 'frozen')),
  CONSTRAINT food_storage_policies_method
    CHECK (storage_method IN ('pantry', 'fridge', 'freezer')),
  CONSTRAINT food_storage_policies_suitability
    CHECK (suitability IN ('recommended', 'allowed', 'forbidden', 'unknown')),
  CONSTRAINT food_storage_policies_duration
    CHECK (
      (suitability = 'forbidden' AND duration_days IS NULL)
      OR (suitability <> 'forbidden' AND (duration_days IS NULL OR duration_days > 0))
    ),
  CONSTRAINT food_storage_policies_expiry_kind
    CHECK (expiry_kind IN ('DLC', 'DDM', 'estimate', 'unknown')),
  CONSTRAINT food_storage_policies_confidence
    CHECK (confidence >= 0 AND confidence <= 1),
  CONSTRAINT food_storage_policies_temperature
    CHECK (min_temperature_c IS NULL OR max_temperature_c IS NULL OR min_temperature_c <= max_temperature_c)
);

CREATE UNIQUE INDEX IF NOT EXISTS food_storage_policies_canonical_unique
  ON public.food_storage_policies (
    canonical_food_id, food_state, purchase_state, storage_method
  )
  WHERE archetype_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS food_storage_policies_archetype_unique
  ON public.food_storage_policies (
    archetype_id, food_state, purchase_state, storage_method
  )
  WHERE canonical_food_id IS NULL;

CREATE INDEX IF NOT EXISTS food_storage_policies_lookup_canonical
  ON public.food_storage_policies (canonical_food_id, active)
  WHERE canonical_food_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS food_storage_policies_lookup_archetype
  ON public.food_storage_policies (archetype_id, active)
  WHERE archetype_id IS NOT NULL;

ALTER TABLE public.food_storage_policies ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.food_storage_policies FROM anon, authenticated;
GRANT SELECT ON TABLE public.food_storage_policies TO authenticated;

DROP POLICY IF EXISTS food_storage_policies_authenticated_read
  ON public.food_storage_policies;
CREATE POLICY food_storage_policies_authenticated_read
  ON public.food_storage_policies
  FOR SELECT
  TO authenticated
  USING (true);

COMMENT ON TABLE public.food_storage_policies IS
  'Règles de conservation versionnées. suitability=forbidden est distinct de duration_days NULL (inconnu).';


-- Traçabilité des décisions sur les lots --------------------------------------
ALTER TABLE public.inventory_lots
  ADD COLUMN IF NOT EXISTS storage_decision_source text NOT NULL DEFAULT 'legacy',
  ADD COLUMN IF NOT EXISTS storage_decision_confidence numeric,
  ADD COLUMN IF NOT EXISTS storage_policy_version text,
  ADD COLUMN IF NOT EXISTS expiration_source text NOT NULL DEFAULT 'legacy',
  ADD COLUMN IF NOT EXISTS expiration_kind text NOT NULL DEFAULT 'unknown',
  ADD COLUMN IF NOT EXISTS requires_storage_review boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS label_use_by_date date,
  ADD COLUMN IF NOT EXISTS label_best_before_date date;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'inventory_lots_storage_confidence_check'
      AND conrelid = 'public.inventory_lots'::regclass
  ) THEN
    ALTER TABLE public.inventory_lots
      ADD CONSTRAINT inventory_lots_storage_confidence_check
      CHECK (
        storage_decision_confidence IS NULL
        OR storage_decision_confidence BETWEEN 0 AND 1
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'inventory_lots_expiration_kind_check'
      AND conrelid = 'public.inventory_lots'::regclass
  ) THEN
    ALTER TABLE public.inventory_lots
      ADD CONSTRAINT inventory_lots_expiration_kind_check
      CHECK (expiration_kind IN ('DLC', 'DDM', 'estimate', 'unknown'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS inventory_lots_storage_review_idx
  ON public.inventory_lots (user_id, acquired_on DESC)
  WHERE requires_storage_review = true;

COMMENT ON COLUMN public.inventory_lots.storage_decision_source IS
  'Origine du lieu retenu : étiquette/achat, politique, catalogue, règle de sécurité ou confirmation utilisateur.';
COMMENT ON COLUMN public.inventory_lots.expiration_source IS
  'Origine de la date : label_use_by, label_best_before, storage_policy, catalogue, règle conservatrice ou unknown.';


-- Politiques initiales : volailles crues --------------------------------------
-- Le congélateur est autorisé mais jamais choisi par défaut sans achat surgelé
-- ou action explicite de l'utilisateur.
WITH poultry AS (
  SELECT id, canonical_name,
         NULLIF(shelf_life_days_fridge, 0) AS fridge_days,
         NULLIF(shelf_life_days_freezer, 0) AS freezer_days
  FROM public.canonical_foods
  WHERE lower(canonical_name) IN ('pintade', 'poulet', 'dinde', 'canard', 'oie', 'caille')
)
INSERT INTO public.food_storage_policies (
  canonical_food_id, food_state, purchase_state, storage_method,
  suitability, duration_days, expiry_kind,
  min_temperature_c, max_temperature_c,
  source_type, source_ref, confidence, policy_version, reason
)
SELECT id, 'raw', 'any', 'pantry',
       'forbidden', NULL, 'unknown', NULL, NULL,
       'curated_safety', 'Myko conservation policy v1', 0.99,
       'storage-v1-2026-07-13', 'Volaille crue : garde-manger interdit'
FROM poultry
UNION ALL
SELECT id, 'raw', 'any', 'fridge',
       'recommended', COALESCE(fridge_days, 2), 'estimate', 0, 4,
       'curated_safety', 'Myko catalogue + chaîne du froid', 0.98,
       'storage-v1-2026-07-13', 'Volaille fraîche : réfrigérateur par défaut'
FROM poultry
UNION ALL
SELECT id, 'raw', 'any', 'freezer',
       'allowed', COALESCE(freezer_days, 180), 'estimate', -24, -18,
       'curated_catalog', 'Myko canonical_foods', 0.90,
       'storage-v1-2026-07-13', 'Congélation possible si achetée surgelée ou choisie explicitement'
FROM poultry
ON CONFLICT (canonical_food_id, food_state, purchase_state, storage_method)
  WHERE archetype_id IS NULL
DO UPDATE SET
  suitability       = EXCLUDED.suitability,
  duration_days      = EXCLUDED.duration_days,
  expiry_kind        = EXCLUDED.expiry_kind,
  min_temperature_c = EXCLUDED.min_temperature_c,
  max_temperature_c = EXCLUDED.max_temperature_c,
  source_type        = EXCLUDED.source_type,
  source_ref         = EXCLUDED.source_ref,
  confidence         = EXCLUDED.confidence,
  policy_version     = EXCLUDED.policy_version,
  reason             = EXCLUDED.reason,
  verified_at        = now(),
  active             = true,
  updated_at         = now();

-- Les anciens champs restent lus pendant la transition. Zéro y signifie
-- désormais explicitement « garde-manger interdit » pour la volaille crue.
UPDATE public.canonical_foods
SET shelf_life_days_pantry = 0,
    updated_at = now()
WHERE lower(canonical_name) IN ('pintade', 'poulet', 'dinde', 'canard', 'oie', 'caille')
  AND shelf_life_days_pantry IS DISTINCT FROM 0;


-- Réparation de sécurité -------------------------------------------------------
-- On corrige uniquement les lots reliés DIRECTEMENT à un canonique de volaille.
-- Ils sont marqués à contrôler car la base ne peut pas déplacer physiquement le
-- produit ni lire sa véritable DLC sur l'emballage.
UPDATE public.inventory_lots AS lot
SET storage_method = 'fridge',
    storage_place = 'Frigo',
    expiration_date = CASE
      WHEN lot.expiration_date IS NULL THEN lot.acquired_on + COALESCE(NULLIF(food.shelf_life_days_fridge, 0), 2)
      ELSE LEAST(
        lot.expiration_date,
        lot.acquired_on + COALESCE(NULLIF(food.shelf_life_days_fridge, 0), 2)
      )
    END,
    storage_decision_source = 'safety_data_repair',
    storage_decision_confidence = 0.98,
    storage_policy_version = 'storage-v1-2026-07-13',
    expiration_source = 'canonical_catalog',
    expiration_kind = 'estimate',
    requires_storage_review = true
FROM public.canonical_foods AS food
WHERE lot.canonical_food_id = food.id
  AND lot.storage_method = 'pantry'
  AND lower(food.canonical_name) IN ('pintade', 'poulet', 'dinde', 'canard', 'oie', 'caille');


-- Vérification bloquante -------------------------------------------------------
DO $$
DECLARE
  unsafe_count integer;
BEGIN
  SELECT count(*) INTO unsafe_count
  FROM public.inventory_lots lot
  JOIN public.canonical_foods food ON food.id = lot.canonical_food_id
  WHERE lot.storage_method = 'pantry'
    AND lower(food.canonical_name) IN ('pintade', 'poulet', 'dinde', 'canard', 'oie', 'caille');

  IF unsafe_count <> 0 THEN
    RAISE EXCEPTION 'Migration conservation : % lot(s) de volaille encore au garde-manger', unsafe_count;
  END IF;
END $$;
