name: Export Supabase Data (CSV + ZIP via pooler 6543)

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    env:
      DB_NAME: postgres
      DB_PORT: 6543
      DB_SSL: require
    steps:
      - uses: actions/checkout@v4

      - name: Install PostgreSQL client & zip
        run: sudo apt-get update && sudo apt-get install -y postgresql-client zip

      - name: Test secrets visibility
        run: |
          echo "HOST length: $(echo -n '${{ secrets.SUPABASE_POOLER_HOST }}' | wc -c)"
          echo "REF length: $(echo -n '${{ secrets.SUPABASE_PROJECT_REF }}' | wc -c)"
          echo "PWD length: $(echo -n '${{ secrets.SUPABASE_DB_PASSWORD }}' | wc -c)"

      - name: Test connection to Supabase
        env:
          PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_HOST: ${{ secrets.SUPABASE_POOLER_HOST }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          set -e
          echo "Testing connection to $SUPABASE_HOST:$DB_PORT as postgres.${SUPABASE_PROJECT_REF} ..."
          psql -h "$SUPABASE_HOST" -p "$DB_PORT" -d "$DB_NAME" -U "postgres.${SUPABASE_PROJECT_REF}" -c "select version();"

      - name: Export all tables to CSV
        env:
          PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_HOST: ${{ secrets.SUPABASE_POOLER_HOST }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          set -e
          rm -rf data_export && mkdir -p data_export
          echo "# Data export summary" > data_summary.md
          echo "_Generated: $(date -u)_  " >> data_summary.md
          echo >> data_summary.md

          echo "Listing public tables..."
          TABLES=$(psql -h "$SUPABASE_HOST" -p "$DB_PORT" -d "$DB_NAME" -U "postgres.${SUPABASE_PROJECT_REF}" -Atc "select tablename from pg_tables where schemaname='public' order by tablename;")

          for T in $TABLES; do
            echo "Exporting $T ..."
            psql -h "$SUPABASE_HOST" -p "$DB_PORT" -d "$DB_NAME" -U "postgres.${SUPABASE_PROJECT_REF}" -c "\copy public.\"$T\" to 'data_export/${T}.csv' csv header"
            CNT=$(psql -h "$SUPABASE_HOST" -p "$DB_PORT" -d "$DB_NAME" -U "postgres.${SUPABASE_PROJECT_REF}" -Atc "select count(*) from public.\"$T\";")
            echo "- **$T**: \`$CNT\` rows" >> data_summary.md
          done

      - name: Zip CSVs
        run: |
          cd data_export
          zip -9 -r ../data-csv.zip .
          cd -
          echo "Created data-csv.zip"

      - name: Upload CSV ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-data-csv
          path: data-csv.zip
