name: Export Supabase Schema (final fix)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  dump:
    runs-on: ubuntu-latest
    env:
      DB_NAME: postgres
      DB_PORT: 6543
      DB_SSL: require
    steps:
      - uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Test connection to Supabase (using pooler user)
        env:
          PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_HOST: ${{ secrets.SUPABASE_POOLER_HOST }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          set -e
          echo "Testing connection to $SUPABASE_HOST:$DB_PORT ..."
          psql "host=$SUPABASE_HOST port=$DB_PORT dbname=$DB_NAME user=postgres.${SUPABASE_PROJECT_REF} sslmode=$DB_SSL" -Atc "select version();"

      - name: Generate schema.md from database
        env:
          PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_HOST: ${{ secrets.SUPABASE_POOLER_HOST }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          echo "Generating schema.md ..."
          psql "host=$SUPABASE_HOST port=$DB_PORT dbname=$DB_NAME user=postgres.${SUPABASE_PROJECT_REF} sslmode=$DB_SSL" \
            -v ON_ERROR_STOP=1 -f tools/schema_report.sql > schema.md
          echo "✅ schema.md generated successfully."

      - name: Upload schema.md as artifact
        uses: actions/upload-artifact@v4
        with:
          name: schema-report
          path: schema.md
