name: Export Supabase Data (CSV + ZIP, mirror schema connection)

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    env:
      DB_NAME: postgres
      DB_PORT: 6543
      DB_SSL: require
    steps:
      - uses: actions/checkout@v4

      - name: Install PostgreSQL client & zip
        run: sudo apt-get update && sudo apt-get install -y postgresql-client zip

      - name: Build connection string (mirror schema)
        id: conn
        run: |
          echo "CONN=host=${{ secrets.SUPABASE_POOLER_HOST }} port=6543 dbname=postgres user=postgres sslmode=require options=project=${{ secrets.SUPABASE_PROJECT_REF }}" >> $GITHUB_OUTPUT

      - name: Test connection (same as schema)
        env:
          PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          CONN: ${{ steps.conn.outputs.CONN }}
        run: |
          set -e
          echo "Testing connection..."
          psql "$CONN" -Atc "select version();"

      - name: Export all public tables to CSV
        env:
          PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          CONN: ${{ steps.conn.outputs.CONN }}
        run: |
          set -e
          rm -rf data_export && mkdir -p data_export
          echo "# Data export summary" > data_summary.md
          echo "_Generated: $(date -u)_  " >> data_summary.md
          echo >> data_summary.md

          echo "Listing public tables..."
          TABLES=$(psql "$CONN" -Atc "select tablename from pg_tables where schemaname='public' order by tablename;")

          for T in $TABLES; do
            echo "Exporting $T ..."
            psql "$CONN" -c "\copy public.\"$T\" to 'data_export/${T}.csv' csv header"
            CNT=$(psql "$CONN" -Atc "select count(*) from public.\"$T\";")
            echo "- **$T**: \`$CNT\` rows" >> data_summary.md
          done

      - name: Zip CSVs
        run: |
          cd data_export
          zip -9 -r ../data-csv.zip .
          cd -
          echo "Created data-csv.zip"

      - name: Upload CSV ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-data-csv
          path: data-csv.zip

      - name: Commit data_summary.md to repository
        if: success()
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data_summary.md
          if git diff --cached --quiet; then
            echo "No changes in data_summary.md, skipping commit."
          else
            git commit -m "chore(data): update data_summary.md"
            git push
          fi
