name: Export Supabase Schema (psql on pooler 6543)

on:
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Test connection (Mode A: user=postgres + options=project=REF)
        env:
          PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          HOST: ${{ secrets.SUPABASE_POOLER_HOST }}
          REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          set -e
          echo "HOST=$HOST  REF=$REF"
          psql "host=$HOST port=6543 dbname=postgres user=postgres sslmode=require options=project=$REF" -Atc "select version();"

      - name: Generate schema.md
        env:
          PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          HOST: ${{ secrets.SUPABASE_POOLER_HOST }}
          REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          psql "host=$HOST port=6543 dbname=postgres user=postgres sslmode=require options=project=$REF" \
            -v ON_ERROR_STOP=1 \
            -f tools/schema_report.sql > schema.md

      - name: Upload schema.md
        uses: actions/upload-artifact@v4
        with:
          name: schema-report
          path: schema.md
